CREATE SEQUENCE SEQ_SEMAFORO
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;




CREATE TABLE TBL_SEMAFORO (
    SEMAFORO_ID INTEGER DEFAULT SEQ_SEMAFORO.NEXTVAL NOT NULL,
    LOCALIZACAO VARCHAR2(255) NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    TEMPO_VERDE INT NOT NULL,
    TEMPO_AMARELO INT NOT NULL,
    TEMPO_VERMELHO INT NOT NULL
);
